-- tests/unit/core/lib/schema_spec.lua
local schema = require("core.lib.schema")

describe("schema", function()
  describe("new()", function()
    it("returns a fresh instance", function()
      local s = schema.new()
      assert.is_table(s)
    end)

    it("starts with build_spec registered", function()
      local s = schema.new()
      assert.is_table(s:get("build_spec"))
    end)

    it("starts with plugin_spec registered", function()
      local s = schema.new()
      assert.is_table(s:get("plugin_spec"))
      assert.is_table(s:get("plugin_spec").source)
      assert.is_true(s:get("plugin_spec").source.required)
    end)

    it("starts with keymap_entry registered", function()
      local s = schema.new()
      assert.is_table(s:get("keymap_entry"))
    end)

    it("starts with autocmd_entry registered", function()
      local s = schema.new()
      assert.is_table(s:get("autocmd_entry"))
    end)

    it("returns instances that do not share state", function()
      local s1 = schema.new()
      local s2 = schema.new()
      s1:extend("plugin_spec", { custom_field = { type = "string" } })
      assert.is_table(s1:get("plugin_spec").custom_field)
      assert.is_nil(s2:get("plugin_spec").custom_field)
    end)
  end)

  describe(":extend", function()
    it("merges new fields into an existing schema", function()
      local s = schema.new()
      s:extend("plugin_spec", { extra = { type = "string" } })
      assert.is_table(s:get("plugin_spec").extra)
      assert.equal("string", s:get("plugin_spec").extra.type)
      assert.is_table(s:get("plugin_spec").source)
    end)

    it("creates a new schema if the name does not exist", function()
      local s = schema.new()
      s:extend("custom_thing", { foo = { type = "string" } })
      assert.is_table(s:get("custom_thing"))
      assert.equal("string", s:get("custom_thing").foo.type)
    end)
  end)

  describe(":replace", function()
    it("swaps an existing schema entirely", function()
      local s = schema.new()
      s:replace("plugin_spec", { only = { type = "string" } })
      assert.is_table(s:get("plugin_spec").only)
      assert.is_nil(s:get("plugin_spec").source)
    end)
  end)

  describe("default() singleton", function()
    it("returns the same instance on repeated calls", function()
      local a = schema.default()
      local b = schema.default()
      assert.equal(a, b)
    end)
  end)

  describe("module-level convenience API", function()
    it("schema.get delegates to default", function()
      assert.is_table(schema.get("plugin_spec"))
    end)

    it("schema.extend mutates the default instance", function()
      schema.extend("plugin_spec", { convenience_marker = { type = "string" } })
      assert.is_table(schema.default():get("plugin_spec").convenience_marker)
      schema.default():get("plugin_spec").convenience_marker = nil
    end)
  end)
end)
