return {
  source = "LuxVim/nvim-luxline",
  debug_name = "nvim-luxline",
  event = "VeryLazy",
  opts = {
    right_active_items_winbar_NvimTree = {},
    right_inactive_items_winbar_NvimTree = {},
    left_active_items_winbar_terminal = { "windownumber" },
    left_inactive_items_winbar_terminal = { "windownumber" },
    right_active_items_winbar_terminal = {},
    right_inactive_items_winbar_terminal = {},
    left_active_items = { "filename:tail", "git:status" },
    left_inactive_items = {},
    right_active_items = { "position", "filetype:icon", "encoding:short" },
    right_inactive_items = { "filename:tail" },
    winbar_enabled = true,
    winbar_disabled_filetypes = { "luxterm_main", "luxterm_preview" },
    left_active_items_winbar = { "windownumber" },
    left_inactive_items_winbar = { "windownumber" },
    right_active_items_winbar = { "modified", "filename:tail" },
    right_inactive_items_winbar = { "modified", "filename:tail" },
    left_separator = "",
    right_separator = "",
    left_separator_winbar = "▶",
    right_separator_winbar = "◀",
    update_throttle = 20,
    git_cache_timeout = 5000,
    git_diff_debounce = 200,
    git_enabled = true,
    default_theme = "default",
  },
}
